import {
  Controller,
  Post,
  UploadedFile,
  UseInterceptors,
  Body,
  Req,
  UseGuards,
  BadRequestException,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { diskStorage } from 'multer';
import { FilesService } from './filesforuser.service';
import { UploadFileDto } from './dto/UploadFileDto';
import { JwtAuthGuard } from 'src/auth/jwt-auth.guard';
import { extname } from 'path';
import { Request } from 'express';
import { ApiTags, ApiBearerAuth, ApiOperation, ApiConsumes, ApiBody, ApiCreatedResponse, ApiBadRequestResponse, ApiUnauthorizedResponse } from '@nestjs/swagger';
import { Get } from '@nestjs/common';
import { ApiParam } from '@nestjs/swagger';
import { FileListItemDto } from './dto/FileListItemDto';
import { ApiOkResponse } from '@nestjs/swagger';
import { ApiNotFoundResponse } from '@nestjs/swagger';
import { Param } from '@nestjs/common';
import { ParseUUIDPipe } from '@nestjs/common';
import { NotFoundException } from '@nestjs/common';
import { Delete } from '@nestjs/common';
import { ApiQuery } from '@nestjs/swagger';
import { Query } from '@nestjs/common';

/**
 * Single endpoint controller for uploading files.
 *
 * - Uses JwtAuthGuard to ensure only authenticated users can upload.
 * - Uses multer diskStorage to write files into uploads dir.
 * - Storage filename is generated by FilesService.generateStorageName to ensure
 *   consistent naming and avoid collisions / path issues.
 *
 * Notes:
 * - The controller expects the FilesService and a FileRepository implementation
 *   (PrismaFileRepository) to be registered in the same module.
 * - The uploaded file field name is "file".
 */
@ApiBearerAuth('access-token')
@ApiTags('Files')
@UseGuards(JwtAuthGuard)
@Controller('files')
export class FilesController {
  // Limit default max file size (bytes)
  private readonly maxFileSize = Number(process.env.MAX_FILE_SIZE ?? 10 * 1024 * 1024); // 10MB

  constructor(private readonly filesService: FilesService) {}

  @Post()
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Upload a file (authenticated users only)' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    description: 'Multipart form with file and optional metadata.',
    schema: {
      type: 'object',
      properties: {
        file: { type: 'string', format: 'binary' },
        isPublic: { type: 'boolean', example: false },
      },
      required: ['file'],
    },
  })
  @ApiCreatedResponse({
    description: 'File metadata created',
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        originalName: { type: 'string' },
        storageName: { type: 'string' },
        mimeType: { type: 'string' },
        size: { type: 'number' },
        isPublic: { type: 'boolean' },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
  })
  @ApiBadRequestResponse({ description: 'Invalid request or missing file' })
  @ApiUnauthorizedResponse({ description: 'Unauthorized' })
  @UseInterceptors(
    FileInterceptor('file', {
      limits: { fileSize: Number(process.env.MAX_FILE_SIZE ?? 10 * 1024 * 1024) },
      storage: diskStorage({
        destination: (req, file, cb) => {
          const dir = process.env.UPLOADS_DIR ?? './uploads';
          cb(null, dir);
        },
        filename: (req: Request & { user?: any }, file, cb) => {
          try {
            const { v4: uuidv4 } = require('uuid');
            const ext = extname(file.originalname) || '';
            const storageName = `${uuidv4()}${ext}`;
            cb(null, storageName);
          } catch (err) {
            cb(err as any, file.originalname);
          }
        },
      }),
    }),
  )
  async upload(
    @UploadedFile() file: Express.Multer.File,
    @Body() dto: UploadFileDto,
    @Req() req: Request & { user?: any },
  ) {
    // Basic validation: multer will enforce fileSize; make sure a file is present.
    if (!file) {
      throw new BadRequestException('File is required');
    }

    // Extract owner/user id from the authenticated request user.
    // Your JwtAuthGuard may populate req.user.id or req.user.sub depending on implementation.
    const user = req.user as any;
    const ownerId: string = user?.id ?? user?.sub;
    if (!ownerId) {
      throw new BadRequestException('Authenticated user id not found on request');
    }

    // Delegate to service which will create DB metadata record.
    const created = await this.filesService.uploadFile(ownerId, file, {
      isPublic: dto?.isPublic,
    });

    // Return the created metadata (you may want to map or sanitize before returning).
    return {
      id: created.id,
      originalName: created.originalName,
      storageName: created.storageName,
      mimeType: created.mimeType,
      size: created.size,
      isPublic: created.isPublic,
      createdAt: created.createdAt,
    };
  }

  @Get('allthefiles')
  @ApiOperation({ summary: 'List all files (no filters)' })
  @ApiOkResponse({ description: 'Array of all file metadata', type: FileListItemDto, isArray: true })
  async listAll(): Promise<FileListItemDto[]> {
    return this.filesService.listAll();
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get file metadata by id' })
  @ApiParam({
    name: 'id',
    description: 'UUID of the file metadata record',
    example: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
  })
  @ApiOkResponse({ description: 'File metadata', type: FileListItemDto })
  @ApiNotFoundResponse({ description: 'File not found' })
  async getById(
    @Param('id', new ParseUUIDPipe()) id: string,
  ): Promise<FileListItemDto> {
    const file = await this.filesService.findById(id);
    if (!file) throw new NotFoundException(`File with id ${id} not found`);
    return file;
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Delete file metadata by id' })
  @ApiParam({
    name: 'id',
    description: 'UUID of the file metadata record to delete',
    example: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
  })
  @ApiOkResponse({ description: 'Deleted file metadata', type: FileListItemDto })
  @ApiNotFoundResponse({ description: 'File not found' })
  async deleteById(
    @Param('id', new ParseUUIDPipe()) id: string,
  ): Promise<FileListItemDto> {
    const deleted = await this.filesService.deleteById(id);
    if (!deleted) throw new NotFoundException(`File with id ${id} not found`);
    return deleted;
  }

  @Get('owner/:ownerId')
  @ApiOperation({ summary: 'List files by owner with simple pagination' })
  @ApiParam({
    name: 'ownerId',
    description: 'UUID of the owner (user) whose files to list',
    example: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
  })
  @ApiQuery({ name: 'skip', required: false, description: 'Number of items to skip', type: Number, example: 0 })
  @ApiQuery({ name: 'take', required: false, description: 'Number of items to return', type: Number, example: 25 })
  @ApiOkResponse({ description: 'Array of file metadata', type: FileListItemDto, isArray: true })
  async listByOwner(
    @Param('ownerId', new ParseUUIDPipe()) ownerId: string,
    @Query('skip') skip?: string,
    @Query('take') take?: string,
  ): Promise<FileListItemDto[]> {
    const s = Number(skip ?? 0);
    const t = Number(take ?? 25);
    return this.filesService.listByOwner(ownerId, s, t);
  }

  @Get('url/:id')
  @ApiOperation({ summary: 'Get public URL for a stored file by id' })
  @ApiParam({
    name: 'id',
    description: 'UUID of the file metadata record',
    required: true,
    example: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
  })
  @ApiOkResponse({
    description: 'Object containing public URL for the file',
    schema: { type: 'object', properties: { url: { type: 'string', example: 'http://localhost:3000/uploads/abcd-1234.png' } } },
  })
  @ApiNotFoundResponse({ description: 'File not found or URL not available' })
  async getUrlById(@Param('id', new ParseUUIDPipe()) id: string) {
    const url = await this.filesService.getUrlById(id);
    if (!url) throw new NotFoundException(`URL for file id ${id} not found`);
    return { url };
  }

}